name: imagegalery
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any
  build_runner: ^2.4.11
  auto_route: ^8.1.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^4.2.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^8.1.0
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.1
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  flutter_shimmer: ^2.1.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true
  generated: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/webant_logo.png
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: assets/images/webant_logo.png

